### ISSUE TITLE
grid() mixin

### ISSUE THREAD

**Issue by rolandtoth** [aaronjamesyoung/simplest-flexbox-grid#2]
I've created a mixin to simplify adding grids.

Example: create 1-3-1 columns:

```
.grid {
  @include grid(1,3,1);
}
```

Feel free to include or modify:

https://gist.github.com/rolandtoth/e3b7cc9f1cdb36862292deeb82ee56ab

**Comment by aaronjamesyoung** [comment]
Thank you, that's a sweet idea! I'll play with it a bit and get it added in for sure.

**Comment by rolandtoth** [comment]
Thanks - I purposedly used arglist instead list because for me it's easier to remember grid(1,2) instead grid(1 2). But of course list is also fine for me.

**Comment by rolandtoth** [comment]
Just updated the gist because the mixin couldn't use gutter and padding. I also renamed it to `_fg_grid`, just to follow some naming conventions :) 

Now it accepts three parameters:

- columns list, eg. `1 3 2`
- gutter, eg. `24`
- padding, eg. `32`

I think it's complete now, and perhaps it could replace the main _fg() mixin too, at least I see no use case where that would be more beneficial.

**Comment by rolandtoth** [comment]
Me again - just made another update that fallbacks to _fg() if only a number is passed instead of a list. Now it really replaces the original _fg() mixin plus optionally allows to set individual column widths in one step when passing a list.

**Comment by aaronjamesyoung** [comment]
Cool, thanks! I will have some time this weekend to review and get it merged in!

**Comment by aaronjamesyoung** [comment]
Awesome. I'll have some time this weekend to review and get it merged in!

**Comment by aaronjamesyoung** [comment]
This is good. I'm making a minor modification: changing line 27 of your gist to:

`& > :nth-child(#{length($colList)}n+#{$i}) {`

It looks like a lot of gibberish but basically it means your `1 3 2` layout can potentially repeat over several rows:

```
1 3 2
1 3 2
1 3 2
```

etc.

I'm also renaming your mixin to `_fg()` and my original one to `_fg_grid()` since yours is the one that people will generally be calling from now on. It is backwards-compatible of course.

I need to write some documentation and make the README better in this repo. I'll get that done later today and get it all pushed up. Thanks!

**Comment by rolandtoth** [comment]
Great addition, thanks!

**Comment by rolandtoth** [comment]
Something like 3n+0 isn't enough? That could work using one selector instead two.

**Comment by aaronjamesyoung** [comment]
haha, you're right and I also did my math a little wrong. I'll get the kinks worked out :)

**Comment by aaronjamesyoung** [comment]
OK - I've written some documentation and pushed this all up in bf0e1d39598ed09ebf1b4fc61a2456d9d3277216. Pretty sure I got my math and selectors all right now. Codepen updated too.

Roland - Thanks again! Good job - this is really useful.

**Comment by rolandtoth** [comment]
Great news, thanks! In the Credits section it sounds nice that I provided new SCSS info but most of them were new to me beforehand as well :)
