### ISSUE TITLE
Stylus Port

### ISSUE THREAD

**Issue by Narkoleptika** [aaronjamesyoung/simplest-flexbox-grid#4]
Why hello there Mr. Young (My freshman year band teacher).

Some of my coworkers found this library about a year ago and we've since used it in a lot of projects. It truly is the simplest flexbox grid!

I personally like to use stylus as my preprocessor, so I ended up making a stylus port of this library that I've used in a handful of my own projects.

I meant to open a pull request when I started the port and am just now getting around to it.

I'm just not sure if you're even interested in merging a stylus port (maintenance time, transposing updates, etc), but if you are, I have a branch ready to be made into a pull request!

https://github.com/Narkoleptika/simplest-flexbox-grid/tree/stylus

Going with the assumption that you'd totally be down with this, I made the following changes:

* I moved the sass files into the sass directory
* I added the stylus equivalent files to the stylus directory
* Inside each of those directories, I added a sub README file for the implementation details in the corresponding language.
* I removed the implementation details from the main README
* I Made the main readme more language agnostic
* Added a link to each language directory in the main README
* I forked your demo pen, ported that to stylus, and linked in the stylus README and under the sass demo pen in the main README
* Added syntax highlighting to all of the code blocks

Take a look and if you're interested, lemme know and I'll create a pull request.

**Comment by aaronjamesyoung** [comment]
Joey! Good to hear from you and thanks for reaching out! I'm glad this has been useful to you guys. I haven't used stylus but I do like its simplicity and readability. Your port looks good.

Going forward, I'm not sure there will be many updates to this. I expect that in my next major project I'll be using CSS Grid to handle document-level layouts. That said, updates or fixes can come up from time to time. It shouldn't be too bad to port those one direction or the other.

I'm leaning toward merging it in, although we also could keep it in your separate repo, which I'd link in the readme. Either way would be fine with me; do you have a preference?

Thanks for getting some of those details too, like syntax highlighting.

**Comment by Narkoleptika** [comment]
Css grid is awesome! I agree that it is the ideal grid solution. However, since some users don't like good browsers, I now see this project as the fallback of choice.

Considering that I haven't added anything new conceptually, I think the best approach would be one repo to rule them all.

Before I create a pull request, are there any changes you'd like me to make? Structural, copy or otherwise?

**Comment by aaronjamesyoung** [comment]
I think what you have is great! I may make the main README a bit more verbose, but I'll take some time and think that through on my end.

Thanks Joey, this is sweet!

**Comment by Narkoleptika** [comment]
No problem, Thank you for accepting my stylus port!

**Comment by aaronjamesyoung** [comment]
Done :100:

**Comment by Narkoleptika** [comment]
Boom! 🙏
